### ISSUE TITLE
C++14

### ISSUE THREAD

**Issue by alexhsamuel** [pypa/auditwheel#125]
I'm trying to build a Python 3.6 manylinux1 wheel of a [package](https://github.com/alexhsamuel/ora) implemented in C++14.  I perused #39, and also recent traffic on wheel-builders as suggested in that issue, but didn't find too much to guide me.

After some trial and error, I managed to get a [working wheel](https://pypi.org/project/ora/#files) (I think!) via the following process:
1. Scrounge around for a CentOS 5.11 docker image with GCC 5.  I ended up using continuumio/conda_builder_linux.
2. Hack up my setup.py to link `-static-libstdc++ -static-libgcc`.
3. Build the wheel.
4. `auditwheel repair`.

I was wondering,
1. Is this the current recommended practice?  `-static-libstdc++` or bundling libstdc++.so seems unavoidable for C++14 given the CXXABI version restriction.
2. Where can I find out what's up with manylinux2?  And what CXXABI will this allow?
3. Is there any documentation I might have missed?  If not, is there somewhere I could contribute some for posterity or myself in six months when I've forgotten?  It would be wonderful if there were an PyPA-approved method for distributing binary C++14 (or newer) Linux extension modules.  Conda works but I'd like to support non-conda environments too.
4. Any other suggestions?

FWIW I'm not particularly interested in supporting CentOS 5 with my package.  I'm just looking to create a binary Linux wheel that works on reasonably modern systems that I can actually upload to PyPI.

Thanks much in advance.

**Comment by ehashman** [comment]
All that makes sense; sounds like you might be waiting for the CentOS 7-based policy to get native GCC support in manylinux. I'd agree that you will need to continue to statically link libstdc++ (or potentially, dynamically link it and see if `auditwheel repair` correctly vendors it for you).

I am not super surprised that it's challenging to make C++14 work with the manylinux policy, because it's designed to ensure compatibility even on super old production Linux systems. This allows developers to build one wheel, distribute it on PyPI, and have it work for almost everyone. But it's going to cause challenges when you need the latest and greatest C++ support!

**Comment by alexhsamuel** [comment]
Not really "latest and greatest", unfortunately.  C++17 is out for a while now.  GCC 5.2, the first to support C++14, dates back to around the time of Python 3.4.  

I don't think I'm waiting for a CentOS 7 policy to be honest; by then C++ will have moved forward too and I'm no more likely to code in older C++ than in Python 2.7.

It's unfortunate that there isn't better support for Python extensions written in C++.  Not only are there lots of useful C++ libraries useful wrapped in Python, but also for many C++ is the systems programming language of choice.

**Comment by alexhsamuel** [comment]
Well, how can I help?

**Comment by dkoes** [comment]
Since this a top google hit for this problem, I'd like to add it is very important to hide the libstdc++ symbols when linking it in statically with `-Wl,--exclude-libs,ALL`

If you don't do this, you will run into trouble when importing modules that dynamically link the older libstdc++ (e.g., segfaults that only happen if import statements are in a certain order).
