### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by takluyver** [pypa/auditwheel#181]
Should we aim towards a new release? I think most of our changes have been to the test suite, but there are some functional changes like the AUDITWHEEL_PLAT environment variable (#151), and people are missing those in the released version (e.g. https://github.com/pypa/manylinux/issues/323).

What do we want to get in before making a release?

It seems that libcrypt.so.1 should probably be dropped from the library whitelist: https://github.com/pypa/manylinux/issues/305

**Comment by lkollar** [comment]
I'm happy to help out with the release.

We should probably update the manylinux images before making the release with the `libcrypt.so.1` removal so that repairing wheels will work correctly. I'm also wondering (and mentioned on the linked issue) if we should update the manylinux PEPs before making this change.

In any case, there are a few bug fixes we should release even if the `libcrypt.so.1` removal becomes more complicated so we could maybe plan two separate releases if that happens.

All changes since the last release for reference: https://github.com/pypa/auditwheel/compare/2dad10d9dead00c9dbc57427ea6739343fc7577d...master

**Comment by takluyver** [comment]
[I'm about to go offline for a week, so feel free to press ahead with a release in the meantime]

**Comment by lkollar** [comment]
2.1.0 is out: https://pypi.org/project/auditwheel/2.1.0/

**Comment by takluyver** [comment]
Thanks for taking care of that.
