### ISSUE TITLE
manylinux auditwheel installation errors

### ISSUE THREAD

**Issue by Longbowman** [pypa/auditwheel#214]
I wanted to build auditwheel and run a command 
`auditwheel repair dist/*.whl`
I get this two kind of errors on multiple versions of auditwheel installation
`ImportError: cannot import name 'open_for_csv' from 'wheel.util' (/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7`
and 
`auditwheel: error: cannot find the 'patchelf' tool, which is required`
I've tried almost every version of auditwheel installation. could you help correct way to install? 

-------------
OS: Ubuntu 18.04 
Python: 3.6/3.7
installation commands: 
```
python -m pip install --upgrade pip
pip install numpy cython mdtraj
pip install cffi setuptools wheel twine auditwheel
```

**Comment by lkollar** [comment]
The first error is because you either didn't have `wheel` installed, or not the required version. You can install the correct dependencies with `pip install -r requirements.txt`.

You also need to install `patchelf` separately. As it is not a Python tool, you need to install it either with your distribution's package manager or compile it from source.

Unless you have a reason to to use a specific build environment, I recommend the [manylinux Docker images](https://github.com/pypa/manylinux) which contain everything you need for `auditwheel`.

**Comment by Longbowman** [comment]
Thanks. I have find out that docker images work better
