### ISSUE TITLE
Libraries "not found" after repair

### ISSUE THREAD

**Issue by radarhere** [pypa/auditwheel#371]
Over at [pillow-wheels](https://github.com/python-pillow/pillow-wheels), we use [multibuild](https://github.com/multi-build/multibuild) to put together wheels for [Pillow](https://github.com/python-pillow/Pillow).

A while ago, [a user pointed out that](https://github.com/python-pillow/pillow-wheels/issues/255) `ldd` reported "not found" for some libraries within our wheels.

To try and make my question easier to answer, I've put together a reproduction without multibuild - https://github.com/radarhere/pillow-auditwheel. It is a [Dockerfile](https://github.com/radarhere/pillow-auditwheel/blob/main/Dockerfile) that uses a manylinux Docker image, installs Python, compiles zlib, libjpeg-turbo, xz, tiff, creates a Pillow wheel and then repairs it.

Installing that repaired wheel and then running `ldd`, [I get](https://github.com/radarhere/pillow-auditwheel/runs/5225739092#step:3:12561)
```
/usr/local/lib/python3.9/site-packages/Pillow.libs/libtiff-3f8170ad.so.5.7.0:
	linux-vdso.so.1 =>  (0x00007ffd0707f000)
	liblzma-3d86c46e.so.5.2.5 => not found
	libjpeg-27ee4414.so.62.3.0 => not found
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f273cf1e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f273caa8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f273c6da000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f273cdaa000)
```

So, any idea why I'm seeing "not found"? Is this a bug in auditwheel? Is there something I could be doing differently?

Let me know if I need to further simplify my reproduction.

**Comment by mayeut** [comment]
This seems perfectly normal.
Here, `ldd` is ran directly on a grafted library. This never happens when using a python C extension, they're always loaded through the extension which has the correct RPATH allowing for the dynamic loader to find libraries correctly.
e.g. with Pillow 9.0.1 installed, if doing `ldd` directly on liftiff, we get some `not found` output:
```
ldd cp39/lib/python3.9/site-packages/Pillow.libs/libtiff-8e99fb9e.so.5.7.0 
	linux-vdso.so.1 (0x00007ffeea33b000)
	liblzma-d540a118.so.5.2.5 => not found
	libjpeg-62ed1500.so.62.3.0 => not found
	libz-dd453c56.so.1.2.11 => not found
	libm.so.6 => /lib64/libm.so.6 (0x00007ff47b690000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff47b470000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff47b0ab000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff47ba12000)
```
 Calling `ldd` on the python extension, those `not found` disappear:
```
ldd cp39/lib/python3.9/site-packages/PIL/_imaging.cpython-39-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffdfbbc7000)
	libjpeg-62ed1500.so.62.3.0 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libjpeg-62ed1500.so.62.3.0 (0x00007fa824d3c000)
	libopenjp2-430a98fc.so.2.4.0 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libopenjp2-430a98fc.so.2.4.0 (0x00007fa824cb8000)
	libz-dd453c56.so.1.2.11 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libz-dd453c56.so.1.2.11 (0x00007fa824c97000)
	libtiff-8e99fb9e.so.5.7.0 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libtiff-8e99fb9e.so.5.7.0 (0x00007fa824bbc000)
	libxcb-1122e22b.so.1.1.0 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libxcb-1122e22b.so.1.1.0 (0x00007fa824b7f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa82495d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa824598000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fa824216000)
	liblzma-d540a118.so.5.2.5 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/liblzma-d540a118.so.5.2.5 (0x00007fa8241df000)
	libXau-00ec42fe.so.6.0.0 => /root/cp39/lib/python3.9/site-packages/PIL/../Pillow.libs/libXau-00ec42fe.so.6.0.0 (0x00007fa823fda000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa824c66000)
```

> Is there something I could be doing differently?

`zlib` shall not be grafted and is in fact in the whitelist since auditwheel 5.0.0, c.f.  https://github.com/pypa/auditwheel/issues/152

IMHO, if you're building all those libraries and, depending on licensing issues, you might be better off building static libraries.
With the exception of `zlib`, all those libraries are used by exactly one python extension in Pillow so using static libraries will probably also have the added benefit of reducing the wheel size (and most probably speed-up a bit importing the extensions).
`zlib` is kind of an outlier here and for this one, you can either depend on the system one or rebuild as a static library but relying on a rebuilt shared library and grafting (which will fail or be silently ignored once you upgrade auditwheel) is probably not a good idea.
