### ISSUE TITLE
Tests are throwing version exception for patchelf but not failing

### ISSUE THREAD

**Issue by ehashman** [pypa/auditwheel#44]
The tests are full of the following traceback

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.4.3/bin/auditwheel", line 10, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/auditwheel/main.py", line 49, in main
    rval = args.func(args, p)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/auditwheel/main_repair.py", line 81, in execute
    update_tags=args.UPDATE_TAGS)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/auditwheel/repair.py", line 81, in repair_wheel
    new_soname, new_path = copylib(src_path, dest_dir)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/auditwheel/repair.py", line 132, in copylib
    verify_patchelf()
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/travis/virtualenv/python3.4.3/lib/python3.4/site-packages/auditwheel/repair.py", line 37, in verify_patchelf
    version)
ValueError: patchelf  found. auditwheel repair requirespatchelf >= 0.9.
```

Interestingly, the auditwheel tests are not failing, despite the tracebacks thrown.

The problem is that `patchelf --version` doesn't output anything on version 0.9. I've heard @geofft has [submitted a patch to fix this upstream](https://github.com/rmcgibbo/pypatchelf/pull/1), and I've tested & confirmed the patch fixes the bug.

**Comment by ogrisel** [comment]
Indeed this is weird because we do build @njsmith's patched version of patchelf in the Dockerfile. Maybe there is a environment configuration problem for those tests. I don't have time to investigate now but if you understand what's going wrong please feel free to submit a PR.

**Comment by matthew-brett** [comment]
Yes, our built patchelf outputs:

```
$ patchelf --version
patchelf 0.9
```

Maybe we just need a `bash -r` to make sure that bash has the right binary?

**Comment by njsmith** [comment]
@ogrisel: this has nothing to do with the patchelf version, and nothing to do with the manylinux docker image. AFAICT there are two bugs here:

(1) the auditwheel tests here fetch the 'pypatchelf' package from pypi, which is a Python wrapper for patchelf, and the wrapper breaks `patchelf --version`. ([pypatchelf fix is here](https://github.com/rmcgibbo/pypatchelf/pull/1)). And since `patchelf --version` is broken, auditwheel's attempt to check the `patchelf` version is also broken. The fix for this is just to merge that PR on pypatchelf and release a new version on PyPI.

(2) (this bug) Somehow the test suite here is "passing", even though it's full of unhandled exception tracebacks. This seems like a bug in the test suite, since generally unhandled exceptions should trigger a test failure.

**Comment by geofft** [comment]
Yup, with the fixed pypatchelf the exception no longer occurs. So the immediate fix is to depend on the version with the fix, once it gets merged. But it does seem worth fixing the fact that the traceback is not fatal, if someone were to have an older (native) patchelf installed.

There's a fixed wheel at https://ldpreload.com/tmp/pypatchelf-0.9_geofft1-cp34-cp34m-linux_x86_64.whl that you're welcome to try if you feel like trusting this binary I built. :)

**Comment by ehashman** [comment]
I'm not sure when this was fixed but it's fixed.
