### ISSUE TITLE
policy.json: Add libXt.so.6 to whilelist

### ISSUE THREAD

**Issue by jcfr** [pypa/auditwheel#78]
Working on creating wheels for VTK, I found out that `libXt.so.6` wasn't specified in [policy.json](https://github.com/pypa/auditwheel/blob/3163c09849c4f71a571e182a6fe3eb6edf4f471a/auditwheel/policy/policy.json#L19-L27) and was copied in `.libs` directory.

Would it make sense to add it ?

What could I do to check that is it reasonable to add this library to the whitelist ? Is it mater of having a consistent API/API across all versions of linux we support ?

See https://en.wikipedia.org/wiki/X_Toolkit_Intrinsics 

Cc: @matthew-brett @thewtex

**Comment by rmcgibbo** [comment]
PEP513 whitelists a few other X related libraries (libX11 , libXext, lib libXrender), so it's possible that the non-inclusion of libXt.so.6 was an oversight and that it should be included by symmetry.

**Comment by njsmith** [comment]
The overarching goal is that manylinux wheels should "just work". This is a somewhat fuzzy criterion. But generally for whitelisted libraries it means they need to (a) have a consistent abi across all glibc-based Linux distros that people actually use, and (b) be installed by default on all the the glibc-based based Linux distros that people actually use (at least in the configurations where they try to use your software).

Unfortunately these are somewhat difficult to check except by shipping a bunch of software and then waiting to see if people complain. The whitelist in PEP 513 was generated by empirically looking at what anaconda and canopy were doing. So it's possible that Xt should be on the whitelist but it just happens that no one noticed; or it could be that they tried using the system Xt at some point but it caused problems so they stopped.

@cournape might happen to remember. You should also check whether it's included in a default Ubuntu desktop install; that's a quick check that might rule this out quickly.

And of course the other thing to consider is, is having libXt in .libs causing any problems? Is this issue one that you care enough about to spend energy on?

If after considering all that you still think it should be whitelisted, then here's what I suggest: somehow force it to be whitelisted locally just for your builds, ship some wheels that don't include it, and then if in 6 months or whatever no one has complained, you can come back to us like "I told you so" and we'll add it to the global whitelist. 

The problem with adding it to the global whitelist preemptively before gathering data is then we might be breaking random other projects that were working just fine until we started suddenly using them as guinea pigs without their knowledge. And without our knowledge either, for that matter...

This does mean that you'd be shipping wheels that technically weren't PEP 513 compliant, but whatever, [it's a PEP, not a cop](https://m.imgur.com/gallery/mSHi8). It's not like pypi validates manylinux wheels for compliance or anything.

On the auditwheel side, this suggests that we might want a convenient way to override the policy file from the command line, in order to run experiments like this? Of course it's possible to override by locally hacking the source and that's certainly doable, but it's nicer not to have to do that.

**Comment by rmcgibbo** [comment]
@njsmith: McGibbon, R., concurring.

**Comment by jcfr** [comment]
Thanks everyone for the details and informative feedback :+1: 

It makes complete sense.

> is having libXt in .libs causing any problems? 

Based on preliminary experiment, copying libXt in the wheel is fine. In that particular case, the libraries are all copied in the `vtk` sub-directory (option `--lib-sdir .` is specified)

> Is this issue one that you care enough about to spend energy on?

Now I have a better understanding and preliminary test are conclusive , I think it will work well.

> convenient way to override the policy file from the command line, in order to run experiments like this?

I don't know yet. For sake of experimentation, I was manually updating the `policy.json` file installed in site-package. If there is a need to go beyond experimentation, I will look into creating a PR.

The time being, I am closing the issue.

Thanks a lot, 
Jc
