### ISSUE TITLE
Provide high-level library API

### ISSUE THREAD

**Issue by letmaik** [pypa/auditwheel#82]
It would be great if this package would offer an API at the same level of the command line interface. My concrete use case is that I'd like to run auditwheel straight from setup.py as a build step after bdist_wheel within a custom command (the same could be done by subclassing build_ext). Currently I'm doing something like:
```py
class bdist_wheel_and_repair(Command):
    user_options = []
    def initialize_options(self):
        pass
    def finalize_options(self):
        pass
    def run(self):
        self.run_command('bdist_wheel')
        if sys.platform.startswith('linux'):
            import auditwheel.main
            import unittest.mock
            wheel_path = next(item[2] for item in self.distribution.dist_files if item[0] == 'bdist_wheel')
            with unittest.mock.patch('sys.argv', [sys.argv[0], 'repair', wheel_path]):
                auditwheel.main.main()
```

How about something like `auditwheel.repair(path)` etc. to avoid mocking `sys.argv`?

**Comment by mayeut** [comment]
As mentioned by @njsmith, this can be done easily with a subprocess.
Having a library API has many other constraints that a CLI does not have. This has been discussed extensively over at `pip` so I won't go into details here on those constraints.

**Comment by FFY00** [comment]
Could this be reconsidered? I have a use-case where I want to use auditwheel in the backend and need a bit more lower level interface than what the CLI provides.

In my use-case in specific, I am writing a backend that packages Meson projects into Python wheels. I use auditwheel to both include system dependencies, so that the wheels can be distributed on PyPI, but also include Meson built artifacts in the wheels.
The issue is that I want to make the inclusion of system libraries optional, as that is undesirable for many distro packagers and/or users. For this, I would need to run the wheel repair process with a custom policy, to only include the Meson artifacts.

I understand that adding an API introduces some constraints, however, I don't think we need a very stable API -- I would just be happy with *an* API. Even though it is not the most user friendly, the current internal API is perfectly capable to achieve what I want with some very minor patching.
So, we could define a fast update cycle and keep the API as is. And in the future maybe work towards with a more curated API, using the experience from the current one as reference.

I am willing to commit some time to helping out here, if needed.
